services:
  mysql:
    container_name: mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
    image: mysql:latest
    ports:
    - 3306:3306/tcp
    restart: always
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web
    links:
    - mysql:mysql
    ports:
    - 80:80/tcp
    restart: always
version: '3.1'

